# Generated by Django 4.2.3 on 2023-09-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='itemorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='aaa', max_length=20)),
                ('orderdate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
            ],
            options={
                'db_table': 'itemorder',
            },
        ),
    ]
