# Generated by Django 4.2.3 on 2023-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_stud'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('qual', models.CharField(choices=[('BDS', 'BDS'), ('MD', 'MD'), ('MBBS', 'MBBS')], max_length=5)),
            ],
            options={
                'db_table': 'vdoctor',
            },
        ),
    ]
