# Generated by Django 4.2.3 on 2023-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_sdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('carname', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
