# Generated by Django 4.2.3 on 2023-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('custname', models.CharField(max_length=25)),
                ('balance', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='acctrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txdate', models.DateField()),
                ('accno', models.IntegerField()),
                ('txtype', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'acctrans',
            },
        ),
    ]
